from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class ScenarioConfig(BaseModel):
    """Structured GridSage scenario state."""

    grid_model: str = Field(default="ieee33", description="Grid model: ieee33, ieee69, ieee123")
    solver: str = Field(default="gurobi", description="Optimization solver")
    start_hour: int = Field(default=0)
    end_hour: int = Field(default=24)
    step_minutes: int = Field(default=60)

    use_pv: bool = Field(default=True)
    use_wind: bool = Field(default=True)
    use_ess: bool = Field(default=True)
    use_sop: bool = Field(default=True)
    use_nop: bool = Field(default=True)
    reconfiguration_mode: Literal["none", "radial_reconfiguration"] = Field(default="radial_reconfiguration")
    selected_reconfiguration_plan_id: str = Field(default="R0")
    available_reconfiguration_plans: List[Dict[str, Any]] = Field(default_factory=list)
    reconfiguration_constraints: Dict[str, Any] = Field(
        default_factory=lambda: {
            "max_switch_operations": 1,
            "allow_open_main_feeder": False,
            "allow_multi_nop": False,
        }
    )

    reward_mode: str = Field(default="grid_operator")
    algo_name: str = Field(default="Baseline")
    mode: str = Field(default="two_stage")
    execution_mode: Literal["train", "evaluate"] = Field(default="evaluate")
    specific_model_name: str = Field(default="")
    target_model_steps: Optional[int] = Field(default=None)
    evaluation_targets: List[Dict[str, Any]] = Field(default_factory=list)
    rl_hyperparams: Dict[str, Any] = Field(default_factory=dict)

    node_overrides: Dict[str, Dict[str, float]] = Field(default_factory=dict)
    disabled_devices: Dict[str, Dict[str, List[str]]] = Field(default_factory=dict)

    global_pv_multiplier: float = Field(default=1.0)
    global_load_multiplier: float = Field(default=1.0)
    global_ev_multiplier: float = Field(default=1.0)

    active_skill_ids: List[str] = Field(default_factory=list)
    scenario_name: str = Field(default="")
    scenario_description: str = Field(default="")
    validation_warnings: List[str] = Field(default_factory=list)
    time_profiles: Dict[str, Any] = Field(default_factory=dict)


class DeltaCommand(BaseModel):
    """Incremental command generated by the LLM."""

    action: Literal[
        "update_config",
        "modify_node",
        "configure_disturbance",
        "set_rl_algo",
        "set_execution_mode",
        "set_specific_model",
    ]
    target: str
    value: Any


class ChatRequest(BaseModel):
    session_id: str
    user_input: str
    api_config: Dict[str, str] = Field(default_factory=dict)


class SkillMatchInfo(BaseModel):
    skill_id: str
    name_cn: str = ""
    name_en: str = ""
    category: str = ""
    description_cn: str = ""
    score: float = 0.0
    role: Literal["primary", "secondary"] = "secondary"


class ValidationMessage(BaseModel):
    level: Literal["info", "warning", "reject"] = "info"
    message: str
    skill_id: Optional[str] = None
    rule_id: Optional[str] = None


class ChatResponse(BaseModel):
    thoughts: str = Field(
        default="",
        description="User-facing explanation. Do not include hidden chain-of-thought.",
    )
    delta_commands: List[DeltaCommand] = Field(default_factory=list)
    status: str = Field(default="success")
    error_msg: Optional[str] = None
    matched_skills: List[SkillMatchInfo] = Field(default_factory=list)
    skill_warnings: List[str] = Field(default_factory=list)
    validation_messages: List[ValidationMessage] = Field(default_factory=list)
    proposed_state_summary: Dict[str, Any] = Field(default_factory=dict)
